### ISSUE TITLE
▷ Processes Epic

### ISSUE THREAD

**Issue by isedwards** [opencdms/process#12]
Basic Python-R integration was demonstrated in late 2020. Review the existing code and suggest the issues that are need to ensure a more robust implementation:

Possible issues include:
- [ ] Seperation of R code (currently embeded in Python)
- [ ] Addition of unit tests for Python and R code
- [ ] Documentation on how to use `opencdms-process` with R
- [ ] Review whether `opencdms-process` can share the same `opencdms` namespace when importing the package or whether the top-level package name must be changed
- [ ] Consider giving an R/Python comparison/cheatsheet (e.g. [this one](https://towardsdatascience.com/cheat-sheet-for-python-dataframe-r-dataframe-syntax-conversions-450f656b44ca) - although Python list is not equivalent to R vector as noted in the comments)
