### ISSUE TITLE
Example processes

### ISSUE THREAD

**Issue by isedwards** [opencdms/process#16]
As a developer I wish to have a template and example (working) process to guide development of pygeoapi processes for use in OpenCDMS. Thie will include documentation on how to specify the inputs / outputs to the process.  Future processes to be developed will include QC related processes, data transformations etc.

- [ ] Template / cookiecutter for process
- [ ] Documentation
- [ ] Live demonstration
- [ ] Unit testing and CI/CD
- [ ] Business rules updated

**Comment by david-i-berry** [comment]
As a developer I wish to have a template and example (working) process to guide development of pygeoapi processes for use in OpenCDMS. Thie will include documentation on how to specify the inputs / outputs to the process.  Future processes to be developed will include QC related processes, data transformations etc.

- [ ] Template / cookiecutter for process
- [ ] Documentation
- [ ] Live demonstration
- [ ] Unit testing and CI/CD
- [ ] Business rules updated

**Comment by isedwards** [comment]
https://github.com/david-i-berry/pygeoapi-process-cookiecutter
https://code.usgs.gov/wma/nhgf/pygeoapi-plugin-cookiecutter
